apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-install
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-install
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-install
    spec:
      containers:
      - name: argocd-install
        image: argoproj/argocd:v2.2.1
        command: ["/bin/bash", "-c"]
        args: ["sleep 3600"]
