apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-project-app
spec:
  project: default
  source:
    repoURL: https://github.com/Rigel0000/cloud-computing-and-devops-project
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
    name: argocd-secret
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
