apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-project-app
spec:
  project: default
  source:
    repoURL: https://github.com/Rigel0000/cloud-computing-and-devops-project
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc/'
    namespace: default
    # Eklenmiş server key bölümü
    config:
      server:
        secretkey:
          # Base64 secret server key'inizi buraya girin
          value: eW91ci1zZWNyZXQta2V5
