apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Deployment
  namespace: default
spec:
  destination:
    name: my-gke-cluster
    namespace: argocd
    server: https://kubernetes.default.svc
  containers:
  - name: cuneytfurkan/my-node-app
    image: my-node-app:1.0
    ports:
    - containerPort: 4000
  project: default
  source:
    path: cloud-computing-and-devops-project/argocd
    repoURL: https://github.com/Rigel0000/cloud-computing-and-devops-project.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
